version: '3.8'

services:
  app:
    build: .
    container_name: realtime_translate_app
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    restart: unless-stopped
