version: '3.8'

services:
  app:
    build: .
    container_name: realtime_translate_app
    ports:
      - "5002:5002"
    command: python app.py
    env_file:
      - .env
    volumes:
      - .:/app

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --no-autoupdate run myapp
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    restart: unless-stopped
