version: '3.8'

services:
  app:
    build: .
    container_name: realtime_translate_app
    ports:
      - "5002:5002"
    command: python app.py
    env_file:
      - .env
    volumes:
      - .:/app