services:
  - type: web
    name: happywecan-app
    plan: free
    runtime: docker
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: SECRET_KEY
        generateValue: true # Let Render generate a random, secure key
      - key: REDIS_URL
        fromService:
          type: redis
          name: happywecan-redis
          property: connectionString
  - type: redis
    name: happywecan-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow internal Render services to connect