services:
  - type: web
    name: happywecan-app
    plan: free
    runtime: docker
    startCommand: "bash -c 'PYTHONPATH=. gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b 0.0.0.0:$PORT app:app'"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: SECRET_KEY
        generateValue: true # Let Render generate a random, secure key
      - key: REDIS_URL
        fromService:
          type: redis
          name: happywecan-redis
    customDomains:
      - name: happywecan.com
  - type: redis
    name: happywecan-redis
    plan: free